# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cf86eb110411cc3cb5cb7ffab13722d77d0f3f30142cedc4fd45f4155e33703c73a2d574d6b0f3dd743f98dadc69ba028027ae1b7e4d8da161feaa903ec33579

test:
  secret_key_base: 913059e2040d788541b63bf74a4e89679f9f67934e39b6f5da3d47238321c5507ffd4c11256993b2a1c6ebdc2a6dcc25fa7d4ad8a6a1c17aa1a75b9647ec4a87

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
